config/routes.rb
Webmentor::Application.routes.draw do
  devise_for :users
  root "pages#home"
  get "main_page" => "pages#main_page"
  get "mentor" => "pages#mentor"
  get "online_resources" => "pages#online_resources"
  get "library" => "pages#library"
  get "dev_schools" => "pages#dev_schools"
  get "rblogs" => "pages#recommended_blogs"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def mentor
  end

  def online_resources
  end

  def library
  end

  def dev_schools
  end

  def recommended_blogs
  end

  def main_page
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Webmentor", root_path, class: "navbar-brand"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
         <li><%= link_to "Home", main_page_path %></li>
         <li><%= link_to "Mentor", mentor_path %></li> 
         <li><%= link_to "Online Resources", online_resources_path %></li>
         <li><%= link_to "Library", library_path %></li>
         <li><%= link_to "Dev Schools", dev_schools_path %></li>
         <li><%= link_to "Recommended Blogs", rblogs_path %></li>
         <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webmentor</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
<%= yield %>
</div>

</body>
</html>

app/views/pages/dev_schools.html.erb
<h1>Pages#dev_schools</h1>
<p>Find me in app/views/pages/dev_schools.html.erb</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to Web Mentor</h1>
     <% if user_signed_in? %>
          Feel free to browse around.
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/pages/online_resources.html.erb
<h1>Click the name of subject for reference links.</h1>


<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Ruby
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
      <div class="accordion-inner">
        <a href="http://www.tryruby.org">tryruby</a>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
        Ruby on Rails
      </a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
      <div class="accordion-inner">
       <a href="http://ruby.railstutorial.org/ruby-on-rails-tutorial-book">Michael Hartl's Rails Tutorial</a>
      </div>
    </div>
  </div>
</div>